In [1]:
import numpy as np
import pandas as pd
from scipy import stats

from matplotlib import pyplot as plt
%matplotlib inline

По данным опроса, 75% работников ресторанов утверждают, что испытывают на работе существенный стресс, оказывающий негативное влияние на их личную жизнь. Крупная ресторанная сеть опрашивает 100 своих работников, чтобы выяснить, отличается ли уровень стресса работников в их ресторанах от среднего. 67 из 100 работников отметили высокий уровень стресса.

Посчитайте достигаемый уровень значимости, округлите ответ до четырёх знаков после десятичной точки.

H0: уровень стресса не отличается от среднего |
H1: уровень стресса выше среднего

In [98]:
round(stats.binom_test(67, 100, 0.75), 4)

0.0822

The Wage Tract — заповедник в округе Тома, Джорджия, США, деревья в котором не затронуты деятельностью человека со времён первых поселенцев. Для участка заповедника размером 200х200 м имеется информация о координатах сосен (sn — координата в направлении север-юг, we — в направлении запад-восток, обе от 0 до 200).

Проверим, можно ли пространственное распределение сосен считать равномерным, или они растут кластерами.

Загрузите данные, поделите участок на 5х5 одинаковых квадратов размера 40x40 м, посчитайте количество сосен в каждом квадрате (чтобы получить такой же результат, как у нас, используйте функцию scipy.stats.binned_statistic_2d).

Если сосны действительно растут равномерно, какое среднее ожидаемое количество сосен в каждом квадрате? В правильном ответе два знака после десятичной точки.

In [40]:
pines = pd.read_csv('pines.txt', delimiter='\t')

In [41]:
xbins, ybins = np.arange(0, 240, 40), np.arange(0, 240, 40)
result = stats.binned_statistic_2d(pines.values[:, 0], pines.values[:, 1], None, 'count', bins=[xbins, ybins])
print(result.statistic)

[[18. 26. 29. 25. 20.]
 [14. 12. 22. 34. 25.]
 [12. 24. 15. 50. 37.]
 [ 8. 19. 31. 50.  7.]
 [ 7.  8. 37. 27. 27.]]


In [96]:
observed_frequences = np.concatenate([*result.statistic])
observed_frequences.mean()

23.36

Чтобы сравнить распределение сосен с равномерным, посчитайте значение статистики хи-квадрат для полученных 5х5 квадратов. Округлите ответ до двух знаков после десятичной точки.

In [90]:
chi2 = stats.chisquare(observed_frequences, ddof=0)

In [93]:
round(chi2.statistic, 2), chi2.pvalue

(150.59, 2.574669774967279e-20)